apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
spec:
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: currencyservice
        ports:
        - name: grpc
          containerPort: 7000
        envFrom:
        - configMapRef:
            name: lightstep-configmap
        env:
        - name: PORT
          value: "7000"
        # Lightstep config
        # - name: OTEL_LOG_LEVEL
        #  value: DEBUG
        - name: LS_SERVICE_NAME
          value: currencyservice
        - name: LS_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: lightstep-credentials
              key: accessToken
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7000"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7000"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
spec:
  type: ClusterIP
  selector:
    app: currencyservice
  ports:
  - name: grpc
    port: 7000
    targetPort: 7000
